/**
 * Crash Games Data Registry
 * Auto-generated by scripts/build-crash-games-index.ts
 * Do not edit manually
 */

import type { CrashGameData, CrashGameRegistry } from './types';

import { _1000xbusta } from './1000xbusta';
import { aviator } from './aviator';
import { bustabit } from './bustabit';
import { highflyer } from './highflyer';
import { spaceXy } from './space-xy';
import { spaceman } from './spaceman';

export const crashGameRegistry: CrashGameRegistry = {
  '1000xbusta': _1000xbusta,
  'aviator': aviator,
  'bustabit': bustabit,
  'highflyer': highflyer,
  'space-xy': spaceXy,
  'spaceman': spaceman,
};

/**
 * Get crash game data by slug
 */
export function getCrashGame(slug: string): CrashGameData | undefined {
  return crashGameRegistry[slug];
}

/**
 * Get all crash game data
 */
export function getAllCrashGames(): CrashGameData[] {
  return Object.values(crashGameRegistry);
}

/**
 * Get all crash game slugs
 */
export function getCrashGameSlugs(): string[] {
  return Object.keys(crashGameRegistry);
}

/**
 * Get crash games by category
 */
export function getCrashGamesByCategory(
  category: 'guide' | 'variant' | 'strategy' | 'review'
): CrashGameData[] {
  return getAllCrashGames().filter((cg) => cg.category === category);
}

/**
 * Get crash games by provider
 */
export function getCrashGamesByProvider(provider: string): CrashGameData[] {
  return getAllCrashGames().filter(
    (cg) =>
      cg.provider?.toLowerCase().includes(provider.toLowerCase()) ||
      cg.providerJa?.includes(provider)
  );
}

/**
 * Get crash games by volatility
 */
export function getCrashGamesByVolatility(
  volatility: 'low' | 'medium' | 'high' | 'very-high'
): CrashGameData[] {
  return getAllCrashGames().filter((cg) => cg.volatility === volatility);
}

/**
 * Get crash games with provably fair
 */
export function getProvablyFairCrashGames(): CrashGameData[] {
  return getAllCrashGames().filter((cg) => cg.provablyFair === true);
}

/**
 * Get crash games by difficulty
 */
export function getCrashGamesByDifficulty(
  difficulty: 'beginner' | 'intermediate' | 'advanced'
): CrashGameData[] {
  return getAllCrashGames().filter((cg) => cg.difficulty === difficulty);
}

/**
 * Get casinos that offer a specific crash game
 */
export function getCasinosForCrashGame(slug: string): string[] {
  const cg = getCrashGame(slug);
  return cg?.recommendedCasinos || [];
}

/**
 * Search crash games by name
 */
export function searchCrashGames(query: string): CrashGameData[] {
  const lowerQuery = query.toLowerCase();
  return getAllCrashGames().filter(
    (cg) =>
      cg.name.toLowerCase().includes(lowerQuery) ||
      cg.nameJa.includes(query) ||
      cg.slug.includes(lowerQuery)
  );
}

// Re-export types
export type { CrashGameData, CrashGameRegistry } from './types';
