/**
 * Live Casino Data Registry
 * Auto-generated by scripts/build-live-casino-index.ts
 * Do not edit manually
 */

import type { LiveCasinoData, LiveCasinoRegistry } from './types';

import { evolutionSuperSpeedBaccarat } from './evolution-super-speed-baccarat';
import { japaneseRoulette } from './japanese-roulette';
import { japaneseSpeedBaccarat } from './japanese-speed-baccarat';
import { liveBaccarat } from './live-baccarat';
import { liveBlackjack } from './live-blackjack';
import { liveCraps } from './live-craps';
import { livePoker } from './live-poker';
import { liveRoulette } from './live-roulette';

export const liveCasinoRegistry: LiveCasinoRegistry = {
  'evolution-super-speed-baccarat': evolutionSuperSpeedBaccarat,
  'japanese-roulette': japaneseRoulette,
  'japanese-speed-baccarat': japaneseSpeedBaccarat,
  'live-baccarat': liveBaccarat,
  'live-blackjack': liveBlackjack,
  'live-craps': liveCraps,
  'live-poker': livePoker,
  'live-roulette': liveRoulette,
};

/**
 * Get live casino data by slug
 */
export function getLiveCasino(slug: string): LiveCasinoData | undefined {
  return liveCasinoRegistry[slug];
}

/**
 * Get all live casino data
 */
export function getAllLiveCasino(): LiveCasinoData[] {
  return Object.values(liveCasinoRegistry);
}

/**
 * Get all live casino slugs
 */
export function getLiveCasinoSlugs(): string[] {
  return Object.keys(liveCasinoRegistry);
}

/**
 * Get live casino guides by game type
 */
export function getLiveCasinoByGameType(
  gameType: 'baccarat' | 'blackjack' | 'roulette' | 'poker' | 'craps' | 'other'
): LiveCasinoData[] {
  return getAllLiveCasino().filter((lc) => lc.gameType === gameType);
}

/**
 * Get live casino guides by category
 */
export function getLiveCasinoByCategory(
  category: 'guide' | 'variant' | 'rules' | 'strategy'
): LiveCasinoData[] {
  return getAllLiveCasino().filter((lc) => lc.category === category);
}

/**
 * Get live casino guides by provider
 */
export function getLiveCasinoByProvider(provider: string): LiveCasinoData[] {
  return getAllLiveCasino().filter(
    (lc) =>
      lc.provider?.toLowerCase().includes(provider.toLowerCase()) ||
      lc.providerJa?.includes(provider)
  );
}

/**
 * Get live casino guides with Japanese tables
 */
export function getJapaneseLiveCasino(): LiveCasinoData[] {
  return getAllLiveCasino().filter((lc) => lc.hasJapaneseTable === true);
}

/**
 * Get live casino guides by difficulty
 */
export function getLiveCasinoByDifficulty(
  difficulty: 'beginner' | 'intermediate' | 'advanced'
): LiveCasinoData[] {
  return getAllLiveCasino().filter((lc) => lc.difficulty === difficulty);
}

/**
 * Get casinos that offer a specific live game
 */
export function getCasinosForLiveCasino(slug: string): string[] {
  const lc = getLiveCasino(slug);
  return lc?.recommendedCasinos || [];
}

/**
 * Search live casino guides by name
 */
export function searchLiveCasino(query: string): LiveCasinoData[] {
  const lowerQuery = query.toLowerCase();
  return getAllLiveCasino().filter(
    (lc) =>
      lc.name.toLowerCase().includes(lowerQuery) ||
      lc.nameJa.includes(query) ||
      lc.slug.includes(lowerQuery)
  );
}

// Re-export types
export type { LiveCasinoData, LiveCasinoRegistry } from './types';
