/**
 * Build Live Casino Index Script
 * Auto-generates content/data/live-casino/index.ts from all live casino data files
 *
 * Usage:
 *   npx tsx scripts/build-live-casino-index.ts
 */

import fs from 'fs/promises';
import path from 'path';

const DATA_DIR = path.join(process.cwd(), 'content', 'data', 'live-casino');
const INDEX_FILE = path.join(DATA_DIR, 'index.ts');

/**
 * Convert slug to valid TypeScript variable name
 */
function slugToVarName(slug: string): string {
  // Handle slugs that start with numbers
  let name = slug;
  if (/^\d/.test(name)) {
    name = '_' + name;
  }
  // Convert kebab-case to camelCase
  return name.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

async function main(): Promise<void> {
  console.log('=== Building Live Casino Index ===\n');

  // Get all .ts files except types.ts and index.ts
  const files = await fs.readdir(DATA_DIR);
  const dataFiles = files.filter(
    (f) => f.endsWith('.ts') && f !== 'types.ts' && f !== 'index.ts'
  );

  console.log(`Found ${dataFiles.length} live casino data files\n`);

  // Extract slugs
  const slugs = dataFiles.map((f) => f.replace('.ts', '')).sort();

  // Generate imports
  const imports = slugs
    .map((slug) => {
      const varName = slugToVarName(slug);
      return `import { ${varName} } from './${slug}';`;
    })
    .join('\n');

  // Generate registry entries
  const registryEntries = slugs
    .map((slug) => {
      const varName = slugToVarName(slug);
      return `  '${slug}': ${varName},`;
    })
    .join('\n');

  // Generate the index file content
  const indexContent = `/**
 * Live Casino Data Registry
 * Auto-generated by scripts/build-live-casino-index.ts
 * Do not edit manually
 */

import type { LiveCasinoData, LiveCasinoRegistry } from './types';

${imports}

export const liveCasinoRegistry: LiveCasinoRegistry = {
${registryEntries}
};

/**
 * Get live casino data by slug
 */
export function getLiveCasino(slug: string): LiveCasinoData | undefined {
  return liveCasinoRegistry[slug];
}

/**
 * Get all live casino data
 */
export function getAllLiveCasino(): LiveCasinoData[] {
  return Object.values(liveCasinoRegistry);
}

/**
 * Get all live casino slugs
 */
export function getLiveCasinoSlugs(): string[] {
  return Object.keys(liveCasinoRegistry);
}

/**
 * Get live casino guides by game type
 */
export function getLiveCasinoByGameType(
  gameType: 'baccarat' | 'blackjack' | 'roulette' | 'poker' | 'craps' | 'other'
): LiveCasinoData[] {
  return getAllLiveCasino().filter((lc) => lc.gameType === gameType);
}

/**
 * Get live casino guides by category
 */
export function getLiveCasinoByCategory(
  category: 'guide' | 'variant' | 'rules' | 'strategy'
): LiveCasinoData[] {
  return getAllLiveCasino().filter((lc) => lc.category === category);
}

/**
 * Get live casino guides by provider
 */
export function getLiveCasinoByProvider(provider: string): LiveCasinoData[] {
  return getAllLiveCasino().filter(
    (lc) =>
      lc.provider?.toLowerCase().includes(provider.toLowerCase()) ||
      lc.providerJa?.includes(provider)
  );
}

/**
 * Get live casino guides with Japanese tables
 */
export function getJapaneseLiveCasino(): LiveCasinoData[] {
  return getAllLiveCasino().filter((lc) => lc.hasJapaneseTable === true);
}

/**
 * Get live casino guides by difficulty
 */
export function getLiveCasinoByDifficulty(
  difficulty: 'beginner' | 'intermediate' | 'advanced'
): LiveCasinoData[] {
  return getAllLiveCasino().filter((lc) => lc.difficulty === difficulty);
}

/**
 * Get casinos that offer a specific live game
 */
export function getCasinosForLiveCasino(slug: string): string[] {
  const lc = getLiveCasino(slug);
  return lc?.recommendedCasinos || [];
}

/**
 * Search live casino guides by name
 */
export function searchLiveCasino(query: string): LiveCasinoData[] {
  const lowerQuery = query.toLowerCase();
  return getAllLiveCasino().filter(
    (lc) =>
      lc.name.toLowerCase().includes(lowerQuery) ||
      lc.nameJa.includes(query) ||
      lc.slug.includes(lowerQuery)
  );
}

// Re-export types
export type { LiveCasinoData, LiveCasinoRegistry } from './types';
`;

  // Write the index file
  await fs.writeFile(INDEX_FILE, indexContent);
  console.log(`Written: ${INDEX_FILE}`);
  console.log(`\nRegistered ${slugs.length} live casino guides:`);
  slugs.forEach((s) => console.log(`  - ${s}`));
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
