/**
 * Build Crash Games Index Script
 * Auto-generates content/data/crash-games/index.ts from all crash game data files
 *
 * Usage:
 *   npx tsx scripts/build-crash-games-index.ts
 */

import fs from 'fs/promises';
import path from 'path';

const DATA_DIR = path.join(process.cwd(), 'content', 'data', 'crash-games');
const INDEX_FILE = path.join(DATA_DIR, 'index.ts');

/**
 * Convert slug to valid TypeScript variable name
 */
function slugToVarName(slug: string): string {
  // Handle slugs that start with numbers
  let name = slug;
  if (/^\d/.test(name)) {
    name = '_' + name;
  }
  // Convert kebab-case to camelCase
  return name.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

async function main(): Promise<void> {
  console.log('=== Building Crash Games Index ===\n');

  // Get all .ts files except types.ts and index.ts
  const files = await fs.readdir(DATA_DIR);
  const dataFiles = files.filter(
    (f) => f.endsWith('.ts') && f !== 'types.ts' && f !== 'index.ts'
  );

  console.log(`Found ${dataFiles.length} crash game data files\n`);

  // Extract slugs
  const slugs = dataFiles.map((f) => f.replace('.ts', '')).sort();

  // Generate imports
  const imports = slugs
    .map((slug) => {
      const varName = slugToVarName(slug);
      return `import { ${varName} } from './${slug}';`;
    })
    .join('\n');

  // Generate registry entries
  const registryEntries = slugs
    .map((slug) => {
      const varName = slugToVarName(slug);
      return `  '${slug}': ${varName},`;
    })
    .join('\n');

  // Generate the index file content
  const indexContent = `/**
 * Crash Games Data Registry
 * Auto-generated by scripts/build-crash-games-index.ts
 * Do not edit manually
 */

import type { CrashGameData, CrashGameRegistry } from './types';

${imports}

export const crashGameRegistry: CrashGameRegistry = {
${registryEntries}
};

/**
 * Get crash game data by slug
 */
export function getCrashGame(slug: string): CrashGameData | undefined {
  return crashGameRegistry[slug];
}

/**
 * Get all crash game data
 */
export function getAllCrashGames(): CrashGameData[] {
  return Object.values(crashGameRegistry);
}

/**
 * Get all crash game slugs
 */
export function getCrashGameSlugs(): string[] {
  return Object.keys(crashGameRegistry);
}

/**
 * Get crash games by category
 */
export function getCrashGamesByCategory(
  category: 'guide' | 'variant' | 'strategy' | 'review'
): CrashGameData[] {
  return getAllCrashGames().filter((cg) => cg.category === category);
}

/**
 * Get crash games by provider
 */
export function getCrashGamesByProvider(provider: string): CrashGameData[] {
  return getAllCrashGames().filter(
    (cg) =>
      cg.provider?.toLowerCase().includes(provider.toLowerCase()) ||
      cg.providerJa?.includes(provider)
  );
}

/**
 * Get crash games by volatility
 */
export function getCrashGamesByVolatility(
  volatility: 'low' | 'medium' | 'high' | 'very-high'
): CrashGameData[] {
  return getAllCrashGames().filter((cg) => cg.volatility === volatility);
}

/**
 * Get crash games with provably fair
 */
export function getProvablyFairCrashGames(): CrashGameData[] {
  return getAllCrashGames().filter((cg) => cg.provablyFair === true);
}

/**
 * Get crash games by difficulty
 */
export function getCrashGamesByDifficulty(
  difficulty: 'beginner' | 'intermediate' | 'advanced'
): CrashGameData[] {
  return getAllCrashGames().filter((cg) => cg.difficulty === difficulty);
}

/**
 * Get casinos that offer a specific crash game
 */
export function getCasinosForCrashGame(slug: string): string[] {
  const cg = getCrashGame(slug);
  return cg?.recommendedCasinos || [];
}

/**
 * Search crash games by name
 */
export function searchCrashGames(query: string): CrashGameData[] {
  const lowerQuery = query.toLowerCase();
  return getAllCrashGames().filter(
    (cg) =>
      cg.name.toLowerCase().includes(lowerQuery) ||
      cg.nameJa.includes(query) ||
      cg.slug.includes(lowerQuery)
  );
}

// Re-export types
export type { CrashGameData, CrashGameRegistry } from './types';
`;

  // Write the index file
  await fs.writeFile(INDEX_FILE, indexContent);
  console.log(`Written: ${INDEX_FILE}`);
  console.log(`\nRegistered ${slugs.length} crash games:`);
  slugs.forEach((s) => console.log(`  - ${s}`));
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
